#!/usr/bin/env bash
# displays a list of currently running processes.
# shows all processes for all users including those which night not have a TTY
# Display in user-oriented format
# Show process hierarchy

ps -auxf

